# <https://github.com/attogram/8queens>
# <https://travis-ci.org/attogram/8queens>
language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly
matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
before_script:
  - composer install
script:
  # Test Install via composer create-project
# - ...
  # PHP Lint all the things
  - if find . -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  # Unit Tests
#  - phpunit tests
